# Generated by Django 4.1.7 on 2023-02-22 07:04

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_sb_admin_interface", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theme",
            name="color_input_focus",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="color_input_focus_border",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="color_primary_dark",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="color_primary_darker",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="color_primary_light",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="color_primary_lighter",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="env_color",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="env_name",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="env_visible_in_favicon",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="env_visible_in_header",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="favicon",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="logo_color",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="logo_max_height",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="logo_max_width",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="logo_visible",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="title",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="title_color",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="title_visible",
        ),
        migrations.AddField(
            model_name="theme",
            name="color_critical",
            field=colorfield.fields.ColorField(
                default="#007d7e", image_field=None, max_length=10, samples=None
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="color_info",
            field=colorfield.fields.ColorField(
                default="#007d7e", image_field=None, max_length=10, samples=None
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="color_positive",
            field=colorfield.fields.ColorField(
                default="#007d7e", image_field=None, max_length=10, samples=None
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="color_secondary",
            field=colorfield.fields.ColorField(
                default="#007d7e", image_field=None, max_length=10, samples=None
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="color_warning",
            field=colorfield.fields.ColorField(
                default="#007d7e", image_field=None, max_length=10, samples=None
            ),
        ),
    ]
