# Generated by Django 4.1.7 on 2023-02-22 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_sb_admin_interface", "0002_remove_theme_color_input_focus_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theme",
            name="sidebar_logo_background_color",
        ),
    ]
