# Generated by Django 4.1.7 on 2023-02-22 07:39

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "wagtail_sb_admin_interface",
            "0003_remove_theme_sidebar_logo_background_color",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="color_critical",
            field=colorfield.fields.ColorField(
                default="#cd4444", image_field=None, max_length=10, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="color_info",
            field=colorfield.fields.ColorField(
                default="#1f7e9a", image_field=None, max_length=10, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="color_positive",
            field=colorfield.fields.ColorField(
                default="#1b8666", image_field=None, max_length=10, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="color_primary",
            field=colorfield.fields.ColorField(
                default="#2e1f5e", image_field=None, max_length=10, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="color_warning",
            field=colorfield.fields.ColorField(
                default="#faa500", image_field=None, max_length=10, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="sidebar_logo_shape",
            field=models.CharField(
                choices=[
                    ("", "Original"),
                    ("circular", "Circular"),
                    ("rectangular", "Rectangular"),
                    ("square", "Square"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
