# Generated by Django 4.1.7 on 2023-02-22 08:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "wagtail_sb_admin_interface",
            "0004_alter_theme_color_critical_alter_theme_color_info_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="theme",
            old_name="sidebar_logo_mobile",
            new_name="sidebar_logo_collapsed",
        ),
    ]
