# Generated by Django 4.1.7 on 2023-02-22 15:48

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "wagtail_sb_admin_interface",
            "0005_rename_sidebar_logo_mobile_theme_sidebar_logo_collapsed",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="sidebar_logo_background_color",
            field=colorfield.fields.ColorField(
                default="#ffffff", image_field=None, max_length=10, samples=None
            ),
        ),
    ]
